language: swift
osx_image: xcode9.3
before_install:
  - brew update
  - brew upgrade swiftlint
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods -v '1.5.3' --no-rdoc --no-ri --no-document --quiet
  - pod --version
  - pod repo update
script:
  - xcodebuild -workspace Xcore.xcworkspace -scheme Example -destination "platform=iOS Simulator,name=iPhone 8,OS=latest" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
